---
title: Mario Dena Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
email: your-email@example.com
author: Mario Dena
description: Fullstack Web-developer Blog
baseurl: '/blog'
url: ''
theme: jekyll-theme-minimal
logo: Photo.jpeg
plugins:
- jekyll-feed
